### ISSUE TITLE
Crash on selection

### ISSUE THREAD

**Issue by xtuc** [bwrsandman/Bless#10]
Reproduce:
- open a wasm file
- select in text
- :boom:

I'm using:
```
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

The error is: `*** Error in 'mono': double free or corruption (out): 0x00005608ff7e3740 ***` or `*** Error in 'mono': free(): invalid pointer: 0x000055793af8f720 ***`

Here's the output:
```
Root element is missing.
Directory '/home/foo/.config/bless/plugins' not found.
Directory '/home/foo/.config/bless/plugins' not found.
Directory '/home/foo/.config/bless/plugins' not found.
Could not find file "/home/foo/.config/bless/export_patterns".
Could not find file "/home/foo/.config/bless/history.xml".
Root element is missing.
Document does not have a root element.
Sharing violation on path /home/foo/.config/bless/preferences.xml
Sharing violation on path /home/foo/.config/bless/preferences.xml
Sharing violation on path /home/foo/.config/bless/preferences.xml
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) GLib.SList.g_free (intptr) <0x0005f>
  at GLib.ListBase.Empty () <0x0013c>
  at GLib.ListBase.Dispose (bool) <0x0000f>
  at GLib.ListBase.Finalize () <0x0001d>
  at (wrapper runtime-invoke) object.runtime_invoke_virtual_void__this__ (object,intptr,intptr,intptr) <0x00068>

Native stacktrace:

	mono(+0xc8514) [0x5608fdf25514]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x13150) [0x7fb584bbc150]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7fb5845e90bb]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x16d) [0x7fb5845eaf5d]
	/lib/x86_64-linux-gnu/libc.so.6(+0x8128d) [0x7fb58463328d]
	/lib/x86_64-linux-gnu/libc.so.6(+0x8864a) [0x7fb58463a64a]
	/lib/x86_64-linux-gnu/libc.so.6(+0x8a73e) [0x7fb58463c73e]
	/lib/x86_64-linux-gnu/libc.so.6(cfree+0x6e) [0x7fb58464144e]
	[0x41ea6b70]

Debug info from gdb:

[New LWP 28063]
[New LWP 28064]
[New LWP 28085]
[New LWP 28086]
[New LWP 28110]
[New LWP 28141]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e2120, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7fb585725780 (LWP 28062) "Main" 0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e2120, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
  2    Thread 0x7fb583bff700 (LWP 28063) "SGen worker" 0x00007fb584bb7072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5608fe418a08) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7fb5842d4700 (LWP 28064) "Finalizer" 0x00007fb584bbba4a in __waitpid (pid=28165, stat_loc=0x7fb5842d256c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  4    Thread 0x7fb570e47700 (LWP 28085) "gmain" 0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7d5570, nfds=2, timeout=3607) at ../sysdeps/unix/sysv/linux/poll.c:29
  5    Thread 0x7fb56bfff700 (LWP 28086) "gdbus" 0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e5ee0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  6    Thread 0x7fb56affd700 (LWP 28110) "pool" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  7    Thread 0x7fb57031c700 (LWP 28141) "Main" 0x00007fb5846b606d in __GI___libc_read (fd=13, buf=0x7fb583d9c988, nbytes=4096) at ../sysdeps/unix/sysv/linux/read.c:26

Thread 7 (Thread 0x7fb57031c700 (LWP 28141)):
#0  0x00007fb5846b606d in __GI___libc_read (fd=13, buf=0x7fb583d9c988, nbytes=4096) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x0000000041e97de0 in  ()
#2  0x00007fb583d9a710 in  ()
#3  0x00007fb583d9a8c0 in  ()
#4  0x00007fb583d9c968 in  ()
#5  0x0000000000000020 in  ()
#6  0x00007fb583d9a570 in  ()
#7  0x00007fb5580019e0 in  ()
#8  0x00007fb57031b810 in  ()
#9  0x00007fb57031b810 in  ()
#10 0x00007fb57031b730 in  ()
#11 0x0000000041e97ba4 in  ()
#12 0x0000000000000065 in  ()
#13 0x6e696f706b636568 in  ()
#14 0x727265746e695f65 in  ()
#15 0x0000000000000000 in  ()

Thread 6 (Thread 0x7fb56affd700 (LWP 28110)):
#0  0x00007fb5846c0a49 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fb57a89580a in g_cond_wait_until () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb57a8242e1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb57a82489c in g_async_queue_timeout_pop () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fb57a8780ee in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fb57a877645 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fb584bb07fc in start_thread (arg=0x7fb56affd700) at pthread_create.c:465
#7  0x00007fb5846c6b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fb56bfff700 (LWP 28086)):
#0  0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e5ee0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fb57a850169 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb57a850502 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb57b29db26 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fb57a877645 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fb584bb07fc in start_thread (arg=0x7fb56bfff700) at pthread_create.c:465
#6  0x00007fb5846c6b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fb570e47700 (LWP 28085)):
#0  0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7d5570, nfds=2, timeout=3607) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fb57a850169 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb57a85027c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb57a8502c1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fb57a877645 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fb584bb07fc in start_thread (arg=0x7fb570e47700) at pthread_create.c:465
#6  0x00007fb5846c6b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fb5842d4700 (LWP 28064)):
#0  0x00007fb584bbba4a in __waitpid (pid=28165, stat_loc=0x7fb5842d256c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00005608fdf255f0 in  ()
#2  0x00007fb584bbc150 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007fb5845e90bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x00007fb5845eaf5d in __GI_abort () at abort.c:90
#5  0x00007fb58463328d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fb58475a528 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#6  0x00007fb58463a64a in malloc_printerr (action=<optimized out>, str=0x7fb58475a8b0 "double free or corruption (out)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5426
#7  0x00007fb58463c73e in _int_free (av=0x7fb58498cc20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4175
#8  0x00007fb58464144e in __GI___libc_free (mem=<optimized out>) at malloc.c:3145
#9  0x0000000041ea6b70 in  ()
#10 0x00005608ff7e3740 in  ()
#11 0x00005608fee5be90 in  ()
#12 0x00005608fee5be90 in  ()
#13 0x0000000000000000 in  ()

Thread 2 (Thread 0x7fb583bff700 (LWP 28063)):
#0  0x00007fb584bb7072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5608fe418a08) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007fb584bb7072 in __pthread_cond_wait_common (abstime=0x0, mutex=0x5608fe418a20, cond=0x5608fe4189e0) at pthread_cond_wait.c:502
#2  0x00007fb584bb7072 in __pthread_cond_wait (cond=0x5608fe4189e0, mutex=0x5608fe418a20) at pthread_cond_wait.c:655
#3  0x00005608fe0ad863 in  ()
#4  0x00007fb584bb07fc in start_thread (arg=0x7fb583bff700) at pthread_create.c:465
#5  0x00007fb5846c6b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fb585725780 (LWP 28062)):
#0  0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e2120, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fb57a850169 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb57a850502 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb580b04727 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#4  0x0000000041e8adda in  ()
#5  0x00007ffece3e3b30 in  ()
#6  0x00007ffece3e3b20 in  ()
#7  0x00005608fee5fbc8 in  ()
#8  0x00007ffece3e3b20 in  ()
#9  0x0000000041e02f70 in  ()
#10 0x00005608fee8ead0 in  ()
#11 0x0000000041e058b8 in  ()
#12 0x00007ffece3e36a0 in  ()
#13 0x00007ffece3e30b0 in  ()
#14 0x0000000041e8ad6c in  ()
#15 0x00007ffece3e36a0 in  ()
#16 0x0000000041e057bc in  ()
#17 0x00007fb583c34678 in  ()
#18 0x0000000000000000 in  ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

/usr/bin/bless: line 3: 28062 Aborted                 (core dumped) mono "/usr/lib/bless/bless.exe" "$@"

Root element is missing.
Directory '/home/foo/.config/bless/plugins' not found.
Directory '/home/foo/.config/bless/plugins' not found.
Directory '/home/foo/.config/bless/plugins' not found.
Could not find file "/home/foo/.config/bless/export_patterns".
Could not find file "/home/foo/.config/bless/history.xml".
Root element is missing.
Document does not have a root element.
Sharing violation on path /home/foo/.config/bless/preferences.xml
Sharing violation on path /home/foo/.config/bless/preferences.xml
Sharing violation on path /home/foo/.config/bless/preferences.xml
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) GLib.SList.g_free (intptr) <0x0005f>
  at GLib.ListBase.Empty () <0x0013c>
  at GLib.ListBase.Dispose (bool) <0x0000f>
  at GLib.ListBase.Finalize () <0x0001d>
  at (wrapper runtime-invoke) object.runtime_invoke_virtual_void__this__ (object,intptr,intptr,intptr) <0x00068>

Native stacktrace:

	mono(+0xc8514) [0x5608fdf25514]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x13150) [0x7fb584bbc150]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7fb5845e90bb]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x16d) [0x7fb5845eaf5d]
	/lib/x86_64-linux-gnu/libc.so.6(+0x8128d) [0x7fb58463328d]
	/lib/x86_64-linux-gnu/libc.so.6(+0x8864a) [0x7fb58463a64a]
	/lib/x86_64-linux-gnu/libc.so.6(+0x8a73e) [0x7fb58463c73e]
	/lib/x86_64-linux-gnu/libc.so.6(cfree+0x6e) [0x7fb58464144e]
	[0x41ea6b70]

Debug info from gdb:

[New LWP 28063]
[New LWP 28064]
[New LWP 28085]
[New LWP 28086]
[New LWP 28110]
[New LWP 28141]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e2120, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7fb585725780 (LWP 28062) "Main" 0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e2120, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
  2    Thread 0x7fb583bff700 (LWP 28063) "SGen worker" 0x00007fb584bb7072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5608fe418a08) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7fb5842d4700 (LWP 28064) "Finalizer" 0x00007fb584bbba4a in __waitpid (pid=28165, stat_loc=0x7fb5842d256c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  4    Thread 0x7fb570e47700 (LWP 28085) "gmain" 0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7d5570, nfds=2, timeout=3607) at ../sysdeps/unix/sysv/linux/poll.c:29
  5    Thread 0x7fb56bfff700 (LWP 28086) "gdbus" 0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e5ee0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  6    Thread 0x7fb56affd700 (LWP 28110) "pool" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  7    Thread 0x7fb57031c700 (LWP 28141) "Main" 0x00007fb5846b606d in __GI___libc_read (fd=13, buf=0x7fb583d9c988, nbytes=4096) at ../sysdeps/unix/sysv/linux/read.c:26

Thread 7 (Thread 0x7fb57031c700 (LWP 28141)):
#0  0x00007fb5846b606d in __GI___libc_read (fd=13, buf=0x7fb583d9c988, nbytes=4096) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x0000000041e97de0 in  ()
#2  0x00007fb583d9a710 in  ()
#3  0x00007fb583d9a8c0 in  ()
#4  0x00007fb583d9c968 in  ()
#5  0x0000000000000020 in  ()
#6  0x00007fb583d9a570 in  ()
#7  0x00007fb5580019e0 in  ()
#8  0x00007fb57031b810 in  ()
#9  0x00007fb57031b810 in  ()
#10 0x00007fb57031b730 in  ()
#11 0x0000000041e97ba4 in  ()
#12 0x0000000000000065 in  ()
#13 0x6e696f706b636568 in  ()
#14 0x727265746e695f65 in  ()
#15 0x0000000000000000 in  ()

Thread 6 (Thread 0x7fb56affd700 (LWP 28110)):
#0  0x00007fb5846c0a49 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fb57a89580a in g_cond_wait_until () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb57a8242e1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb57a82489c in g_async_queue_timeout_pop () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fb57a8780ee in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fb57a877645 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fb584bb07fc in start_thread (arg=0x7fb56affd700) at pthread_create.c:465
#7  0x00007fb5846c6b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fb56bfff700 (LWP 28086)):
#0  0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e5ee0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fb57a850169 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb57a850502 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb57b29db26 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fb57a877645 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fb584bb07fc in start_thread (arg=0x7fb56bfff700) at pthread_create.c:465
#6  0x00007fb5846c6b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fb570e47700 (LWP 28085)):
#0  0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7d5570, nfds=2, timeout=3607) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fb57a850169 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb57a85027c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb57a8502c1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fb57a877645 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fb584bb07fc in start_thread (arg=0x7fb570e47700) at pthread_create.c:465
#6  0x00007fb5846c6b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fb5842d4700 (LWP 28064)):
#0  0x00007fb584bbba4a in __waitpid (pid=28165, stat_loc=0x7fb5842d256c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00005608fdf255f0 in  ()
#2  0x00007fb584bbc150 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007fb5845e90bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x00007fb5845eaf5d in __GI_abort () at abort.c:90
#5  0x00007fb58463328d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fb58475a528 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#6  0x00007fb58463a64a in malloc_printerr (action=<optimized out>, str=0x7fb58475a8b0 "double free or corruption (out)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5426
#7  0x00007fb58463c73e in _int_free (av=0x7fb58498cc20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4175
#8  0x00007fb58464144e in __GI___libc_free (mem=<optimized out>) at malloc.c:3145
#9  0x0000000041ea6b70 in  ()
#10 0x00005608ff7e3740 in  ()
#11 0x00005608fee5be90 in  ()
#12 0x00005608fee5be90 in  ()
#13 0x0000000000000000 in  ()

Thread 2 (Thread 0x7fb583bff700 (LWP 28063)):
#0  0x00007fb584bb7072 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5608fe418a08) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007fb584bb7072 in __pthread_cond_wait_common (abstime=0x0, mutex=0x5608fe418a20, cond=0x5608fe4189e0) at pthread_cond_wait.c:502
#2  0x00007fb584bb7072 in __pthread_cond_wait (cond=0x5608fe4189e0, mutex=0x5608fe418a20) at pthread_cond_wait.c:655
#3  0x00005608fe0ad863 in  ()
#4  0x00007fb584bb07fc in start_thread (arg=0x7fb583bff700) at pthread_create.c:465
#5  0x00007fb5846c6b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fb585725780 (LWP 28062)):
#0  0x00007fb5846ba951 in __GI___poll (fds=0x5608ff7e2120, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fb57a850169 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb57a850502 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb580b04727 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#4  0x0000000041e8adda in  ()
#5  0x00007ffece3e3b30 in  ()
#6  0x00007ffece3e3b20 in  ()
#7  0x00005608fee5fbc8 in  ()
#8  0x00007ffece3e3b20 in  ()
#9  0x0000000041e02f70 in  ()
#10 0x00005608fee8ead0 in  ()
#11 0x0000000041e058b8 in  ()
#12 0x00007ffece3e36a0 in  ()
#13 0x00007ffece3e30b0 in  ()
#14 0x0000000041e8ad6c in  ()
#15 0x00007ffece3e36a0 in  ()
#16 0x0000000041e057bc in  ()
#17 0x00007fb583c34678 in  ()
#18 0x0000000000000000 in  ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

/usr/bin/bless: line 3: 28062 Aborted                 (core dumped) mono "/usr/lib/bless/bless.exe" "$@"
```

**Comment by lithorus** [comment]
Same here on Ubuntu 18.04

**Comment by lithorus** [comment]
Starting it with the command from https://github.com/bwrsandman/Bless/issues/9#issuecomment-408459395 :
```$ TERM=xterm bless myfile```
seems to fix it.

**Comment by bwrsandman** [comment]
This is a fork, please refer to https://github.com/afrantzis/bless
